language: java
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "jjkuDDn+bYZgzAZ8bAPGtzAvEpSiC7G+gaYqcUSTIwMmM91LicRxHBpVsNeOoqaNLXMw97gQxy6EB3uPqq+/nmT6ih0vUvGB91cScefgT16Fn0JDpEgSrj7zWvTCt+kWvtBG6o3ZfFDYQFVFPF6nSadAIVTwEdlfIQaK/ImpSx4="

addons:
  coverity_scan:
    project:
      name: "mibischo/freemind"
      description: "freemind"
    notification_email: m.bischof2@gmail.com
    build_command_prepend: "ant clean"
    build_command:   "ant dist"
    branch_pattern: master
before_script:
 - chmod +x check_for_duplicate_resources.sh
script: ant dist
after_success: ant test